#!/bin/sh
exec_templates=(
  "/opt/Thinkbox/Deadline[{major}]/bin/deadlinemonitor" # linux style
  "/Applications/Deadline[{major}]/DeadlineMonitor{major}.app/Contents/MacOS/DeadlineMonitor{major}" # macos style
)
IFS=: # sets the internal field seperator to ':'
export APPWRAP_EXEC_TEMPLATES="${exec_templates[*]}"
python3 appwrap.py "$@"
