#!/bin/sh
exec_templates=(
  "/usr/local/Nuke[{major}.{minor}v{release}]/Nuke{major}.{minor}" # linux
  "/Applications/Nuke[{major}.{minor}v{release}]/Nuke{major}.{minor}v{release}.app/Contents/MacOS/Nuke{major}.{minor}" # nuke11+ macos style
  "/Applications/Nuke[{major}.{minor}v{release}]/Nuke{major}.{minor}v{release}.app/Contents/MacOS/Nuke{major}.{minor}v{release}" # pre-nuke11 macos style
  "/Applications/Nuke[{major}.{minor}v{release}.Beta{beta}]/Nuke{major}.{minor}v{release}.Beta{beta}.app/Contents/MacOS/Nuke{major}.{minor}" # beta mac os style
)
IFS=: # sets the internal field seperator to ':'
export APPFIND_TEMPLATES="${exec_templates[*]}"
export APPFIND_PR_TOKENS="beta"
appfind "$@"
